In [1]:
import numpy as np
import torch
from grid2vec import *
import json

In [3]:
np.array([])

array([], dtype=float64)

In [9]:
with open('data/str_grid2idx_800.json') as f:
    str_grid2idx = json.load(f)
    f.close()
grid2idx = {eval(c): str_grid2idx[c] for c in list(str_grid2idx)}

dataset = GridEmbeddingDataset(grid2idx, window_size=20, neg_rate=100)
model = Grid2Vec(len(dataset), 256)
cp = torch.load('model/checkpoint_256_299_0_0.694.pth')
model.load_state_dict(cp['model'])
weight2 = np.load("model/grid_embedding_256_0.8.npy")
weight3 = np.load("model/grid_embedding_384_0.73.npy")
print(evaluate_grid2vec(model.input_embedding(), dataset, test_num=500))
print(evaluate_grid2vec(weight2, dataset, test_num=500))
print(evaluate_grid2vec(weight3, dataset, test_num=500))

0.7862
0.7921
0.7029


In [6]:
import json
import numpy as np

file_train = "data/100k_gps_20161101_reformat.json"
file_train = "data/full/gps_20161101_reformat.json"
d = json.load(open(file_train))


In [11]:
traj_512 = [x for x in list(d['traj'].values()) if len(x) < 512]
traj_256 = [x for x in list(d['traj'].values()) if len(x) < 256]
traj_1024 = [x for x in list(d['traj'].values()) if len(x) < 1024]
print(len(traj_256))
print(len(traj_512))
print(len(traj_1024))
print(len(d['traj']))

107869
131503
132946
132951


In [49]:
import random

max_len = 20
traj = [1, 2, 3, 4, 5, 6] * 7

idx = [0] + sorted(random.sample(range(1,len(traj)-1), max_len - 2)) + [len(traj)-1]
array = np.array(traj)[idx]
array

array([1, 4, 1, 3, 5, 6, 3, 5, 6, 3, 4, 2, 5, 1, 3, 4, 1, 2, 5, 6])

In [7]:
import torch

m = torch.ones((5,5))
e = torch.rand((5,5))
m.add_(e)
print(m)
sm = torch.softmax(m,dim=1)
print(sm)
torch.sum()

tensor([[1.2488, 1.5787, 1.1060, 1.1264, 1.7566],
        [1.4038, 1.4460, 1.1559, 1.9803, 1.6719],
        [1.6371, 1.3880, 1.3009, 1.6942, 1.7834],
        [1.2229, 1.9669, 1.4990, 1.0187, 1.5576],
        [1.3838, 1.6400, 1.8443, 1.7607, 1.4661]])
tensor([[0.1723, 0.2396, 0.1494, 0.1524, 0.2863],
        [0.1692, 0.1765, 0.1320, 0.3011, 0.2212],
        [0.2123, 0.1655, 0.1517, 0.2248, 0.2457],
        [0.1507, 0.3172, 0.1986, 0.1229, 0.2106],
        [0.1558, 0.2012, 0.2468, 0.2271, 0.1691]])


tensor([[0.2152, 0.3783, 0.1652, 0.1717, 0.5029],
        [0.2375, 0.2552, 0.1526, 0.5963, 0.3698],
        [0.3476, 0.2297, 0.1973, 0.3808, 0.4383],
        [0.1843, 0.6238, 0.2978, 0.1252, 0.3280],
        [0.2155, 0.3300, 0.4553, 0.3998, 0.2479]])

In [4]:
import json
import random
import numpy as np
import traj_dist.distance as tdist
import pandas as pd


random.seed(19991014)
file_train = "data/100k_gps_20161101_reformat.json"
json_obj = json.load(open(file_train))
origin_trajs = list(json_obj['origin_traj'].values())
N = 5
eps = 21.11
metric_types=['lcss','edr','erp','frechet','discret_frechet','hausdorff','dtw']
trajs_N = origin_trajs[-3:]


In [3]:
df = pd.DataFrame(columns=['self','contort','down_sample','contort_dsp','other1','other2','other3'])
for i in range(N):
    traj = np.array(origin_trajs[i])
    contort = traj + (np.random.rand(traj.shape[0], 2) * 2 - 1) * 0.0001
    idx = [0] + sorted(random.sample(range(1, traj.shape[0] - 1), traj.shape[0] // 2)) + [traj.shape[0] - 1]
    down_sample = traj[idx]
    contort_dsp = contort[idx]

    new = pd.Series({'self':tdist.edr(traj, traj, type_d='spherical', eps=eps),
                    'contort':tdist.edr(traj, contort, type_d='spherical', eps=eps),
                    'down_sample':tdist.edr(traj, down_sample, type_d='spherical', eps=eps),
                    'contort_dsp':tdist.edr(traj, contort_dsp, type_d='spherical', eps=eps),
                    'other1':tdist.edr(traj, np.array(trajs_N[0]), type_d='spherical', eps=eps),
                    'other2':tdist.edr(traj, np.array(trajs_N[1]), type_d='spherical', eps=eps),
                    'other3':tdist.edr(traj, np.array(trajs_N[2]), type_d='spherical', eps=eps)})
    df = df.append(new, ignore_index=True)
df

NameError: name 'pd' is not defined

In [ ]:
import torch 

t = torch.tensor(0.5)

class model(torch.nn.Module):
    def __init__(self):
        super(model, self).__init__()
        self.t = torch.nn.Linear(1,1)
        # self.t = torch.tensor(0.5)
    def forward(self, x):
        return x * t

m = model()
for p in m.parameters():
    print(p)


In [ ]:
import torch

t = torch.rand(2,4)
print(t)
t = t.unsqueeze(1).repeat(1,3,1)
print(t.shape)
print(t)
weight = torch.softmax(torch.ones(3) / torch.arange(1, 3 + 1).float(), dim=0)
output = torch.einsum('bte, t -> be', t, weight)
output

In [1]:
import numpy as np
import math 

math.sqrt((0.0002203750**2 + 0.0001904250**2))

0.00029125044420566987

In [15]:
import json
import numpy as np
import traj_dist.distance as tdist


sp21 = json.load(open("data/100k_gps_20161101_reformat_distance_sp21.json"))
sp30 = json.load(open("data/100k_gps_20161101_reformat_dis_matrix_sp30.json"))
eu00029 = json.load(open("data/100k_gps_20161101_reformat_dis_matrix_eps0.00029.json"))

diff1 = np.mean(np.array(sp21['dis_matrix'])-np.array(eu00029['dis_matrix']))
diff2 = np.mean(np.array(sp30['dis_matrix'])-np.array(eu00029['dis_matrix']))


diff1:0.0004209801355290295
diff2:1.3911618431187805e-05


In [1]:
from t3s import *


timer.tik("prepare data")
dataset_dir = "/home/yqguo/coding/Trajectory/data/"
str_grid2idx = json.load(open(dataset_dir + "str_grid2idx_400.json"))
grid2idx = {eval(c): str_grid2idx[c] for c in list(str_grid2idx)}
dataset = MetricLearningDataset(dataset_dir + "1m_gps_20161101_info.json", grid2idx)
dataloader = torch.utils.data.DataLoader(dataset, batch_size=64, shuffle=True)
test_dataset = MetricLearningDataset(dataset_dir + "100k_gps_20161102_info.json", grid2idx)
model = T3S(vocab_size=len(grid2idx) + 1).cuda()
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)
timer.tok("prepare data")
# train_t3s(model, dataloader, optimizer, epochs=100)

prepare data start
prepare data done, 15.369s after prepare data start


In [24]:
import torch

a = torch.tensor([[1., 1., 1.],
            [2., 2., 2.],
            [3., 3., 3.],
            [4., 4., 4.]])
# a[:, None]
(a.unsqueeze(1)-a).shape
# torch.norm(a.unsqueeze(1)-a, dim=2, p=2)

torch.Size([4, 4, 3])